### ISSUE TITLE
Access to system environment

### ISSUE THREAD

**Issue by toledobastos** [home-assistant-snap/home-assistant-toolbox#1]
Thanks for the awesome work with HA Core. Is there any way you could implement access to the system environment? I'm running HA Core on Ubuntu desktop and I need to run a few bash and Python scripts that won't run in the HA Core Python VENV.

**Comment by jmgiaever** [comment]
Hi,

Have you tried using the classic mode to see if that helps? 

`sudo snap install home-assistant-snap --classic`

**Comment by toledobastos** [comment]
Hi Joachim,

I tried the devmode (sudo snap install home-assistant-snap --devmode), as the classic mode doesnt' seem to allow for any of the interfaces (I need the BlueZ interface). It still didn't give me access to the system environment. I'm now back to confinement: strict, but if --classic would give me access to the sys environment that's something I'd be happy to try. Unfortunately it doesn't seem to be possible to move between installations, so I guess I'd have to start from scratch and lose all the configurations I have in place.

**Comment by jmgiaever** [comment]
Hi, no you can just take backup of the config folder.

Determine the revision your at with `sudo snap info home-assistant-snap` so you know you're copying the correct folder. E.g 

```
ubuntu@home-assistant:~$ sudo snap info home-assistant-snap | grep installed:
installed:           2022.8.7              (524) 470MB -
```
where 524 is the revision.

```
sudo snap stop home-assistant-snap
# Make sure to swap out <revision> with your revision
sudo cp -r /var/snap/home-assistant-snap/<revision> ~/my-ha-config
sudo snap remove --purge home-assistant-snap
sudo snap install home-assistant-snap && sudo snap stop home-assistant-snap
```
now **again** find out which revision you're at again, in case something changed:

```
# Make sure to swap out <revision> with your revision
sudo cp ~/my-ha-config /var/snap/home-assistant-snap/<revision>
sudo snap start home-assistant-snap
```

Let me know how it goes. Unfortunately it's no way of giving access to files in the system level, so if this doesn't work I'll have to see which solutions I can come up with. :)

**Comment by toledobastos** [comment]
That's awesome. I assume the command "sudo snap install home-assistant-snap" should be "sudo snap install home-assistant-snap --classic" but it's great to know that restricted snaps can be copied over to classic snaps with full system access. I was worried about conflicts due to the Python VENV but good to know this isn't an issue.
